In [1]:
# Writing in a file

myFile =open("myFirstTextFile.txt", "w")

myFile.write(str("3\n"))
myFile.write(str("45\n"))
myFile.write(str("83\n"))
myFile.write(str("21\n"))

myFile.close()

In [3]:
#Reading from a file

with open("myFirstTextFile.txt", "r") as readMyFile:
    data = readMyFile.read().replace('\n', ',')

readMyFile.close() 

print(data[-3])

2


In [4]:
# Appending
myFile = open("myFirstTextFile.txt", "a")
myFile.write("How are you?")
myFile.close()

In [5]:
# Write a program to ask a student for their percentage mark and convert this to a grade.
# The conversion will be done in a function called mark_grade 
def percentage(part, whole):
  percentage = 100 * float(part)/float(whole)
  return str(percentage) + "%"

# print(percentage(3, 5))

# Input your mark

userInputPart = float(input("Your Marks = "))
userInputWhole =  float(input("Total Marks Marks = "))

total = percentage(userInputPart, userInputWhole)

print("You got " , total)

You got  56.0%


In [7]:
#  Create a 1D array of numbers from 0 to 9​

import numpy as np

array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
# Create a 3×3 NumPy array of all Boolean value Trues​

boolArray = np.ones(9, dtype=bool)  # Create a Numpy array of 10 True values
newArray = boolArray.reshape(3, 3)  
print('Numpy Array: ')
print(newArray)

# Another method
# Create a 3X3 Numpy array of 3 rows & 3 columns with all True values
bool_arr = np.ones((3,3), dtype=bool)
print('2D Numpy Array: ')
print(bool_arr)


Numpy Array: 
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
2D Numpy Array: 
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [9]:
# Extract all odd numbers from array of 1-10​
array = np.arange(10)
oddNum = np.where(array%2 == 1)
print(f'Array with Odd Numbers: {array[oddNum]}')


Array with Odd Numbers: [1 3 5 7 9]


In [10]:

# Replace all odd numbers in an array of 1-10 with the value -1​
array = np.arange(1, 10)
for i in range(len(array)): 
    if( i % 2 == 1): 
        array[i]=-1 
 
print(array)

[ 1 -1  3 -1  5 -1  7 -1  9]


In [11]:
# Convert a 1D array to a 2D array with 2 rows​

array = np. array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Convert 1D array to a 2D numpy array of 2 rows and 3 columns.
array_2d = np. reshape(array, (2, 5))
print(array_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [12]:
# Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculate totals

a = np. array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np. array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
c = np.dot(a, b)

sum = np.sum(c)
print("Total : ", sum)

Total :  735
